version: '2'
services:
    geotime-app:
        image: geotime
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://geotime-postgresql:5432/GeoTime
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    geotime-postgresql:
        extends:
            file: postgresql.yml
            service: geotime-postgresql
